### ISSUE TITLE
解决了图表左右浮动布局，请问如何实现flex弹性布局？

### ISSUE THREAD

**Issue by sherjf** [caronchen/obsidian-chartsview-plugin#12]
浮动布局解决了固定页面宽度图表并排显示问题，但需指定图表width。比如两个图表并排显示，需分别指定它们的width。这时如果增大obsidian的页面宽度，则图表的右侧会留下空档。如能像flex布局一样，自动根据页面宽度自动调整，效果就更好了。有办法吗？

**Comment by caronchen** [comment]
> 浮动布局解决了固定页面宽度图表并排显示问题，但需指定图表width。比如两个图表并排显示，需分别指定它们的width。这时如果增大obsidian的页面宽度，则图表的右侧会留下空档。如能像flex布局一样，自动根据页面宽度自动调整，效果就更好了。有办法吗？

Facet不能解决你问题吗？

**Comment by sherjf** [comment]
facet支持的图表不多，其实Multiview的方案挺好，可惜支持的图表也有限，另外每个view指定一个data数组也太麻烦，会存在重复现象。

**Comment by sherjf** [comment]
另外facet如何实现不同图表的组合？如pie、column、line组合成一个facet。

**Comment by sherjf** [comment]
经测试，常用的图表确实可以用facet实现flex布局。
