### ISSUE TITLE
Unable to load local *.csv

### ISSUE THREAD

**Issue by ontrou** [caronchen/obsidian-chartsview-plugin#14]
I can't figure out what I am doing wrong:

In Charts View settings, the data path is set:
Data folder `_csv`

The lineData.csv looks like this:
```
year,value
"1991",3
"1992",4
"1993",3.5
"1994",5
"1995",4.9
"1996",6
"1997",7
"1998",9
"1999",13
```

The load csv file line in chartsview:
```
data: lineData.csv
```

I can render the chart by importing the data, but not by loading the same data source.

I can also get your readme example for Mix Chart type to work.

**Comment by sherjf** [comment]
我也无法载入csv文件，无法显示，而使用插入命令正常
[Pie.csv](https://github.com/caronchen/obsidian-chartsview-plugin/files/6816186/Pie.csv)
[Pie.csv](https://github.com/caronchen/obsidian-chartsview-plugin/files/6816190/Pie.csv)
。
```chartsview
type: Pie
data: Pie.csv

options:
  height: 300
  appendPadding: [-30,0,0,0]
  style:
    float: right
  angleField: value
  meta:
    value:
	  formatter: function formatter(v){ return ''.concat(v,'%')}
  colorField: type
  color: ['hsl(200,80%,60%)', 'hsl(160,80%,40%)', 'hsl(30,60%,50%)']
  radius: 0.7
  label:   
    type: spider
    style: 
	  fontSize: 14
	  textAlign: center
 	  fill: 'hsl(35,50%,65%)'
	content: "{name}\n{percentage}"
	#autoRotate: false
  pieStyle: 
    cursor: pointer
  interactions: [{type: element-selected},{type: element-highlight}]
  legend: false
```

**Comment by caronchen** [comment]
> I can't figure out what I am doing wrong:
> 
> In Charts View settings, the data path is set:
> Data folder `_csv`
> 
> The lineData.csv looks like this:
> 
> ```
> year,value
> "1991",3
> "1992",4
> "1993",3.5
> "1994",5
> "1995",4.9
> "1996",6
> "1997",7
> "1998",9
> "1999",13
> ```
> 
> The load csv file line in chartsview:
> 
> ```
> data: lineData.csv
> ```
> 
> I can render the chart by importing the data, but not by loading the same data source.
> 
> I can also get your readme example for Mix Chart type to work.

Sorry, please use 1.0.6 version.

**Comment by caronchen** [comment]
> 我也无法载入csv文件，无法显示，而使用插入命令正常。
> 
> ```
> type: Pie
> data: Pie.csv
> 
> options:
>   height: 300
>   appendPadding: [-30,0,0,0]
>   style:
>     float: right
>   angleField: value
>   meta:
>     value:
> 	  formatter: function formatter(v){ return ''.concat(v,'%')}
>   colorField: type
>   color: ['hsl(200,80%,60%)', 'hsl(160,80%,40%)', 'hsl(30,60%,50%)']
>   radius: 0.7
>   label:   
>     type: spider
>     style: 
> 	  fontSize: 14
> 	  textAlign: center
>  	  fill: 'hsl(35,50%,65%)'
> 	content: "{name}\n{percentage}"
> 	#autoRotate: false
>   pieStyle: 
>     cursor: pointer
>   interactions: [{type: element-selected},{type: element-highlight}]
>   legend: false
> ```
> 
> [Pie.csv](https://github.com/caronchen/obsidian-chartsview-plugin/files/6816190/Pie.csv)

不好意思，用1.0.6的版本吧。
