### ISSUE TITLE
请教双轴图的data数据如何引用？

### ISSUE THREAD

**Issue by sherjf** [caronchen/obsidian-chartsview-plugin#15]
常规图和Mix图的data数据导入可以使用data: xxx.csv，但双轴图DualAxes如何引用，使用data: xxx.csv 和data: [xxx.csv, xxx.csv]均无法解决，请指教，谢谢！

**Comment by caronchen** [comment]
暂时不支持，抽空我实现一下。

**Comment by caronchen** [comment]
> 常规图和Mix图的data数据导入可以使用data: xxx.csv，但双轴图DualAxes如何引用，使用data: xxx.csv 和data: [xxx.csv, xxx.csv]均无法解决，请指教，谢谢！

已实现，版本1.0.7。

**Comment by sherjf** [comment]
您太强了，解决了双轴图的csv文件导入问题。希望能继续更新，加入data-set模块的引用，实现数据转置等功能。

**Comment by caronchen** [comment]
> 您太强了，解决了双轴图的csv文件导入问题。希望能继续更新，加入data-set模块的引用，实现数据转置等功能。

好啊，我先看看。
