### ISSUE TITLE
How to build the Wordcloud Data from a Obsidian note ?

### ISSUE THREAD

**Issue by Parlazo** [caronchen/obsidian-chartsview-plugin#16]
- x: "Word"
    value: 1
    category: "words"

How can i get this data from inside a obsidian note it self in a automated way?

**Comment by caronchen** [comment]
> * x: "Word"
>   value: 1
>   category: "words"
> 
> How can i get this data from inside a obsidian note it self in a automated way?

You could use CSV file.
