### ISSUE TITLE
希望更新下ant-design/charts版本，谢谢！

### ISSUE THREAD

**Issue by sherjf** [caronchen/obsidian-chartsview-plugin#19]
ant-design/charts版本已更新到1.2.7，希望本插件也同步更新下，谢谢！

**Comment by caronchen** [comment]
> ant-design/charts版本已更新到1.2.7，希望本插件也同步更新下，谢谢！

已更新，版本1.0.7。

**Comment by sherjf** [comment]
谢谢！
