### ISSUE TITLE
请教下如何设置坐标轴的formatter？

### ISSUE THREAD

**Issue by sherjf** [caronchen/obsidian-chartsview-plugin#2]
如坐标轴数值要增加百分比%，如何设置formatter？谢谢指教！

**Comment by caronchen** [comment]
不是很理解你的意思，麻烦举个例子？

**Comment by sherjf** [comment]
比如您的以下例子中，要在yAxis坐标轴上的数值后面加上单位名称“个”，看API是通过formatter实现，请教下语法如何写，谢谢！
#-----------------#
#- chart type    -#
#-----------------#
type: DualAxes

#-----------------#
#- chart data    -#
#-----------------#
data:
  -
    - time: "2019-03"
      value: 350
      count: 800
    - time: "2019-04"
      value: 900
      count: 600
    - time: "2019-05"
      value: 300
      count: 400
    - time: "2019-06"
      value: 450
      count: 380
    - time: "2019-07"
      value: 470
      count: 22
  -
    - time: "2019-03"
      value: 350
      count: 800
    - time: "2019-04"
      value: 900
      count: 600
    - time: "2019-05"
      value: 300
      count: 400
    - time: "2019-06"
      value: 450
      count: 380
    - time: "2019-07"
      value: 470
      count: 22

#-----------------#
#- chart options -#
#-----------------#
options:
  xField: 'time'
  yField: ['value', 'count']
  geometryOptions:
    - geometry: 'column'
    - geometry: 'line'
      lineStyle:
	    lineWidth: 2

**Comment by caronchen** [comment]
暂时不支持，抽空这两天我实现一下。

**Comment by caronchen** [comment]
1.0.1版本已经支持了，请更新使用，写法可以参考demo。

**Comment by sherjf** [comment]
高手，确实可以了。
