### ISSUE TITLE
在Mix图表中，无法使用自定义函数，希望能修正下。

### ISSUE THREAD

**Issue by sherjf** [caronchen/obsidian-chartsview-plugin#21]
使用自定义函数，如formatter: function formatter(_ref){},  content: function content(value){}等，均无效。

**Comment by caronchen** [comment]
> 虽然不会报错，但仍然无效，不改变输出。console.log()无法查询，说明函数不起作用。Mix图表的每个view使用options.xxx，是否为这个原因造成？

不好意思，才修复这个问题，确实如你所说，options.xxx形式的配置没有解析导致的。
1.1.1版本已经修复，可以试一下。
