### ISSUE TITLE
能支持下自定义函数吗？

### ISSUE THREAD

**Issue by sherjf** [caronchen/obsidian-chartsview-plugin#26]
实现下图Legend中的itemValue，需要用到自定义函数功能，但目前不支持。
<img width="620" alt="截屏2021-10-01 22 22 03" src="https://user-images.githubusercontent.com/37824950/135636200-141997f9-f4ee-4d7b-83e7-19d43b7b6305.png">

**Comment by caronchen** [comment]
我抽空看一下

**Comment by sherjf** [comment]
除了不支持自定义函数，还不支持数组迭代方法，如.map().filter()等，希望能一并修复下。

**Comment by caronchen** [comment]
给我个例子吧

**Comment by sherjf** [comment]
类似这个[例子](https://codesandbox.io/s/dazzling-panka-z332g)，可以使用自定义外部函数。Facet图表中倒是可以自定义函数，但常规图表不行。
eachView: |
    function eachView(view, f){
	  function ArrayStatistic(array,key) {
	    var obj = array.map((item)=> {   
  	      return item[key]
	    }).reduce((pre,cur)=> {
          if(cur in pre) {
            pre[cur]++    
          }
          else {
          pre[cur] = 1
          }
          return pre
        },{});
	var arr = Object.keys(obj).map((i)=> {  
          return {
            name: i,
            value: obj[i],
          }
        });
		return arr
	  };

**Comment by caronchen** [comment]
1.0.12 版本先试一下，可能跟Bug有关。

**Comment by caronchen** [comment]
能否使用函数需要看Ant Design Charts的文档，文档里的属性如果是支持函数的，都可以使用函数。
