### ISSUE TITLE
Text overlaying other text in pie chart preview

### ISSUE THREAD

**Issue by papojari** [caronchen/obsidian-chartsview-plugin#27]
In pie charts with many little fractions text tends to be displayed over other text or not even be shown because there is too little space.

- Example:
![image](https://user-images.githubusercontent.com/81317317/139594864-4b7bf7cb-c406-4696-86fd-add24607c6a7.png)

I obviously want to be able to read all text (names and percentage of fractions). To fix this the lines extendeing from the fraction to the text of the fraction could be longer for some fractions.

**Comment by caronchen** [comment]
> In pie charts with many little fractions text tends to be displayed over other text or not even be shown because there is too little space.
> 
> * Example:
>   ![image](https://user-images.githubusercontent.com/81317317/139594864-4b7bf7cb-c406-4696-86fd-add24607c6a7.png)
> 
> I obviously want to be able to read all text (names and percentage of fractions). To fix this the lines extendeing from the fraction to the text of the fraction could be longer for some fractions.

Use 'layout' to change text layout type. Options: 'overlap' 、 'fixedOverlap' 、 'limitInShape'

![image](https://user-images.githubusercontent.com/150803/139793829-d2660b3a-7e8e-451a-9f00-2afe7f427980.png)

**Comment by papojari** [comment]
I can't see any change when trying your suggested layout options. I also couldn't find any information about this in the Readme.

**Comment by caronchen** [comment]
> overlap

![image](https://user-images.githubusercontent.com/150803/142765424-590b3d3e-8f37-4705-8fbc-ca3385471fe3.png)

![image](https://user-images.githubusercontent.com/150803/142765449-a51fc95b-c6f8-4cf3-8721-8e5fe49334fc.png)

**Comment by caronchen** [comment]
API docs: https://charts.ant.design/en/examples/pie/basic#basic

![image](https://user-images.githubusercontent.com/150803/142765672-78f267d6-2d65-49b8-943b-56e8c9056825.png)
