### ISSUE TITLE
Error importing linegraph.csv

### ISSUE THREAD

**Issue by ontrou** [caronchen/obsidian-chartsview-plugin#28]
This worked well before, but after recent plugin updates is now giving error message: 组件出错了，请核查后重试： data.filter is not a function.
I imported the line graph like this: data: linegraph.csv
This also gives error message: data.line: linegraph.csv

**Comment by caronchen** [comment]
Show me your sample, thx.

```chartsview
#-----------------#
#- chart type    -#
#-----------------#
type: Line

#-----------------#
#- chart data    -#
#-----------------#
data: LineData.csv

#-----------------#
#- chart options -#
#-----------------#
options:
  xField: 'time'
  yField: 'temperature'
  meta:
    time:
      type: 'time'
      mask: 'MM-DD'
      nice: true
      tickInterval: 172800000
      range: [0, 1]
    temperature:
      sync: 'temperature'
      alias: '温度'
  geometries:
    - type: 'line'
      xField: 'time'
      yField: 'temperature'
    - type: 'point'
      xField: 'time'
      yField: 'temperature'
      mapping:
        shape: 'circle'
        style:
          fillOpacity: 1
```
[LineData.csv](https://github.com/caronchen/obsidian-chartsview-plugin/files/7472242/LineData.csv)

**Comment by ontrou** [comment]
Problem solved. It seems I lost the Charts View Settings at the last Obsidian upgrade (and Templater settings too, but not other plugins). I re-set the data folder for loading chart data, and the chart again rendered properly. I should have checked before posting. Sorry to have bothered you with this.

**Comment by caronchen** [comment]
> Problem solved. It seems I lost the Charts View Settings at the last Obsidian upgrade (and Templater settings too, but not other plugins). I re-set the data folder for loading chart data, and the chart again rendered properly. I should have checked before posting. Sorry to have bothered you with this.

No worries.
