### ISSUE TITLE
WordCount是否支持扫描多个md文档/全库生成词云图

### ISSUE THREAD

**Issue by u2003** [caronchen/obsidian-chartsview-plugin#33]
插件开发者你好呀，觉得你的插件很棒！能直接对单个文档生成词云真的很赞！我是文科技术盲，没有很看明白插件使用说明，想请教一下，这个插件是支持对多个文档/特定文件夹/全库通过WordCount生成词云图的吗，如果可以怎么操作呢。不知道开发者有没有时间解答一下～感谢ww

**Comment by caronchen** [comment]
插件提供了模板，通过命令选择：
![image](https://user-images.githubusercontent.com/150803/149436710-9b4761b7-cdf3-4d76-a3f1-95c4ff85f658.png)

选择其中的“WordCount”：
![image](https://user-images.githubusercontent.com/150803/149436751-1391abf8-d81c-4a06-8511-d817c0c7757c.png)

模板中的“note-name-here-without-fold-path”替换成文件名就好了。
目前不支持指定多个文件，需要的话，我可以实现一下。
你可以把你的需求说一下。

**Comment by u2003** [comment]
谢谢回复！我知道是可以对单一的文档生成词云的哈。我觉得开发者是不是可以再进一步、考虑一下指定多个文件、某个特定的文件夹、甚至是全库生成词云图，这样分析ob库的某个领域的笔记内容就很强大了。开发者超棒，比心心～

**Comment by caronchen** [comment]
> 谢谢回复！我知道是可以对单一的文档生成词云的哈。我觉得开发者是不是可以再进一步、考虑一下指定多个文件、某个特定的文件夹、甚至是全库生成词云图，这样分析ob库的某个领域的笔记内容就很强大了。开发者超棒，比心心～

请更新1.1.3版本试试，实现了你说的功能。有问题反馈，谢谢。
