### ISSUE TITLE
希望加入对特定文件夹调色功能（type: Bar模式下）

### ISSUE THREAD

**Issue by gradyhandle** [caronchen/obsidian-chartsview-plugin#38]
开发者好！
我在看图表时，想要跟踪某个或某些文件夹的变化，希望加入调色功能，这样反馈会更加醒目。我尝试自己改css，但找不到对应的选择器，只能求助。
ps：有老师建议文件夹或标签增加链接功能，也希望可以考虑一下。谢谢！

**Comment by caronchen** [comment]
你好，能否更详细点，或者举个例子？

**Comment by gradyhandle** [comment]
比如这种图里的黄色选中部分
![image](https://user-images.githubusercontent.com/97155298/162700861-4629ebd4-0a07-4152-b90e-0d065156685f.png)
希望可以单独修改它的颜色。

**Comment by caronchen** [comment]
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/150803/162702124-76dc166e-9b3d-4321-b652-2d68c994ebda.png">
默认就是不同颜色的。

**Comment by caronchen** [comment]
```
#-----------------#
#- chart options -#
#-----------------#
options:
  xField: "pv"
  yField: "action"
  seriesField: "action"
  color: |
    function (param) {
      if (param.action == 'Seal the deal2') return 'red';
      return 'blue'; 
    }
  legend:
    position: "top-left"
  conversionTag: {}
```

**Comment by gradyhandle** [comment]
> ```
> #-----------------#
> #- chart options -#
> #-----------------#
> options:
>   xField: "pv"
>   yField: "action"
>   seriesField: "action"
>   color: |
>     function (param) {
>       if (param.action == 'Seal the deal2') return 'red';
>       return 'blue'; 
>     }
>   legend:
>     position: "top-left"
>   conversionTag: {}
> ```

好的，谢谢！我先试试。

**Comment by gradyhandle** [comment]
> 

在数据是常数时可以实现了。不过我的数据是变量：
#-----------------#
#- chart data    -#
#-----------------#
data: | 
  dataviewjs:
  return dv.pages()
           .groupBy(p => p.file.folder)
           .sort(p => p.rows.length)
           .map(p => ({folder: p.key || "ROOT", count: p.rows.length}) )
           .array()
           .reverse();

**Comment by caronchen** [comment]
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/150803/162870311-635ca320-7099-48b1-ab62-2e9ecba46d5d.png">

<img width="439" alt="image" src="https://user-images.githubusercontent.com/150803/162870370-8e308244-a124-43e5-bdab-363e84b8223e.png">

如果你确定要把某个文件夹改一下颜色，也可以用color的。

**Comment by caronchen** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/150803/162871979-3b1d26c2-72d6-4c76-bf9e-ec746b56aebd.png">

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/150803/162872015-aba433e7-a521-47e9-a796-77d551c72c36.png">

也可以按count来定制颜色。

**Comment by gradyhandle** [comment]
> <img alt="image" width="320" src="https://user-images.githubusercontent.com/150803/162871979-3b1d26c2-72d6-4c76-bf9e-ec746b56aebd.png">
> 
> <img alt="image" width="1309" src="https://user-images.githubusercontent.com/150803/162872015-aba433e7-a521-47e9-a796-77d551c72c36.png">
> 
> 也可以按count来定制颜色。

嗯，我之前就是对Java语法不熟悉，尝试过但失败了。谢谢你的耐心指导！👍

**Comment by caronchen** [comment]
是javascript的语法哈。有问题再反馈，感谢支持。

**Comment by gradyhandle** [comment]
> 是javascript的语法哈。有问题再反馈，感谢支持。

😓我一直以为他俩是一回事，哈哈
