### ISSUE TITLE
is it possible to filter non english words?

### ISSUE THREAD

**Issue by yiwc** [caronchen/obsidian-chartsview-plugin#39]

**Comment by caronchen** [comment]
yes

<img width="995" alt="image" src="https://user-images.githubusercontent.com/150803/166852267-c05957a9-ae5f-4a12-b8cc-f44b6219d071.png">

**Comment by caronchen** [comment]
Yes, add or change word filter in plugin settings.

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/150803/166852403-c71a71cf-b4c9-4266-ab4b-a88f81feb853.png">
