### ISSUE TITLE
如何调整图表在Obsidian中的布局？

### ISSUE THREAD

**Issue by sherjf** [caronchen/obsidian-chartsview-plugin#4]
目前图表采用代码块方式，在Obsidian中只能居中或左对齐（调整图表大小），不能实现float、flex等其它布局。请教下如何通过CSS文件调整布局。

**Comment by caronchen** [comment]
div.block-language-chartsview  你可以试一下自定义CSS。

![image](https://user-images.githubusercontent.com/150803/120424549-32893000-c39f-11eb-87b8-117e3a5382b5.png)

**Comment by caronchen** [comment]
#10
