### ISSUE TITLE
Minor correction and question

### ISSUE THREAD

**Issue by bdemirjian** [caronchen/obsidian-chartsview-plugin#43]
This did not work for me...
![image](https://user-images.githubusercontent.com/119558128/216731691-019d4915-04ef-44db-83bf-74caeeba7d50.png)

This did though...
![image](https://user-images.githubusercontent.com/119558128/216731896-1d3df50d-c443-44d3-aee0-ec17a4f134d3.png)
followed by
![image](https://user-images.githubusercontent.com/119558128/216731941-9bc118b3-acd1-4b93-9da3-a3dc69b9e401.png)

Please make the change, as I figured this out by manually editing the example code. :)

Question:

I would like to apply the code block to the file it is in, is there a reserved word for the current file, that I could use?

Thanks!

Brad

**Comment by caronchen** [comment]
Please upgrade plugin to v1.2.1. 
Don't indicate file name for using current file.

```chartsview
#-----------------#
#- chart type    -#
#-----------------#
type: WordCloud

#-----------------#
#- chart data    -#
#-----------------#
data: "wordcount:"

#-----------------#
#- chart options -#
#-----------------#
options:
  wordField: "word"
  weightField: "count"
  colorField: "count"
  wordStyle:
    rotation: 30
```

**Comment by bdemirjian** [comment]
@caronchen Thank you so much, for the fast response!

Moreover, I really like using this plugin w/ your stop words... list.

Here is a great source for stop words..
https://github.com/igorbrigadir/stopwords

And a hint, if you use templates add those words to your stop words list. :)

Be well!
Brad
