### ISSUE TITLE
p.rows.author.array() to show only part of the author field?

### ISSUE THREAD

**Issue by ReaderGuy42** [caronchen/obsidian-chartsview-plugin#45]
```
 .map(p => ({'Date Finished': p.key[1], 'Published in': p.key[0], Count: p.rows.length, 'Title': p.rows.alias.array(), 'Author': p.rows.author.array()}))
```
This is what you helped me with a few weeks ago. In the meantime, I've changed my Author field to look like this `"[[King, Stephen|Stephen King]]" so it would link the book to the author note. 

However, now it your (awesome) scatter plot, the author shows up as that. Is it possible to show the author as just the alias?

Thanks :)

**Comment by caronchen** [comment]
Show me your CodeBlock.

**Comment by caronchen** [comment]
Try to replace `p.rows.author.array()` with `p.rows.author.map(t => t.display ?? t).array()`

**Comment by ReaderGuy42** [comment]
Perfect, thank you :)

**Comment by ReaderGuy42** [comment]
Perfect, thank you!
