### ISSUE TITLE
Feature request: Please add 'scatter' to the chart wizard - because it works ;-)

### ISSUE THREAD

**Issue by merlinuwe** [caronchen/obsidian-chartsview-plugin#47]
Thanks for your GREAT plugin.

I found, that scatter charts are working, when I write

type: Scatter

```chartsview
#-----------------#
#- chart type    -#
#-----------------#
type: Scatter

#-----------------#
#- chart data    -#
#-----------------#
data:
  - label: "1951"
    value: 38
  - label: "1952"
    value: 52
  - label: "1956"
    value: 61
  - label: "1957"
    value: 145
  - label: "1958"
    value: 48

#-----------------#
#- chart options -#
#-----------------#
options:
  xField: label
  yField: value
```

Thank you sooo much for this!

Can you please add it tot the "Charts View: Wizard" (Chart Type Scatter) and "Charts View: Insert Template"?

![image](https://user-images.githubusercontent.com/4138869/235605982-bdafeba7-cf2c-44bd-babd-6db168175ba6.png)

**Comment by caronchen** [comment]
Upgrade to v1.2.3.

**Template:**
<img width="1225" alt="image" src="https://github.com/caronchen/obsidian-chartsview-plugin/assets/150803/197f5039-38a7-404f-8d76-fb86a8d23679">

**Wizard:**
<img width="874" alt="image" src="https://github.com/caronchen/obsidian-chartsview-plugin/assets/150803/f96cf528-a6e1-4a21-b448-cb750e44b516">
