### ISSUE TITLE
Request for Interactive Capabilities in OrganizationTreeGraph

### ISSUE THREAD

**Issue by ishpartko** [caronchen/obsidian-chartsview-plugin#50]
Hello,

I am using your obsidian-chartsview-plugin and it has been a great tool in visualizing data within Obsidian. However, I have a specific need that is currently not met by the plugin, and I'm hopeful that this could be a potential enhancement.

Specifically, I would like to see interactive capabilities added to the OrganizationTreeGraph chart type. The ability to interact with each bar of the graph would greatly improve the utility of the plugin. It would be beneficial if each bar in the graph could be made clickable, such that clicking on a bar would either open a popover with a specified page, or open a specific link.

Ideally, this interaction should be customizable, perhaps through JavaScript, allowing users to handle clicks on each bar as per their specific requirements.

I believe this feature would not only address my need but also be beneficial to many other users who might want to use your plugin for similar purposes.

Looking forward to hearing your thoughts on this.

Best regards,
Ivan

**Comment by caronchen** [comment]
@ishpartko Here's an example.

<img width="812" alt="image" src="https://github.com/caronchen/obsidian-chartsview-plugin/assets/150803/9204b8c1-bb1d-433b-998f-907b483578fc">


```chartsview
#-----------------#
#- chart type    -#
#-----------------#
type: OrganizationTreeGraph

#-----------------#
#- chart data    -#
#-----------------#
data:
  id: "root"
  label: "Root"
  children:
    - id: "c1"
      label: "C1"
      children:
        - id: "c1-1"
          label: "C1-1"
          children:
            - id: "c1-1-1"
              label: "C1-1-1"
            - id: "c1-1-2"
              label: "C1-1-2"
        - id: "c1-2"
          label: "C1-2"
          children:
            - id: "c1-2-1"
              label: "C1-2-1"
            - id: "c1-2-2"
              label: "C1-2-2"
    - id: "c2"
      label: "C2"
      children:
        - id: "c2-1"
          label: "C2-1"
          children:
            - id: "c2-1-1"
              label: "C2-1-1"
              href: "https://obsidian.md"

#-----------------#
#- chart options -#
#-----------------#
options:
  autoFit: true
  fitCenter: true
  onReady: |
     function (graph) {
       graph.on('node:click', (evt) => {
         const { item } = evt;
         const { href } = item.get('model');
         if (href) {
           window.open(href);
         }
       });
     }
```

**Comment by ishpartko** [comment]
@caronchen Thank you very much for the example! I will be happy to apply this in my diagrams!
