### ISSUE TITLE
Allow to use async & await in dataviewjs codeblock

### ISSUE THREAD

**Issue by joyous-coder** [caronchen/obsidian-chartsview-plugin#55]
![Clip_2024-01-08_21-43-36](https://github.com/caronchen/obsidian-chartsview-plugin/assets/42910684/fade8d55-41e6-4e4a-ad08-594bb4af67dc)

This is my code below
![Clip_2024-01-08_21-44-10](https://github.com/caronchen/obsidian-chartsview-plugin/assets/42910684/b320939a-c9e3-408e-bf21-8bc55dcc57eb)

I use customjs to write scripts in obsidian, and this extension load a little slow. I need 'await' until it's ok. Or the block won't get the file DateTimeUtil. Is there anyway I can do this ??

**Comment by caronchen** [comment]
Upgrade to v1.2.7.

<img width="487" alt="image" src="https://github.com/caronchen/obsidian-chartsview-plugin/assets/150803/f1cc866c-ec6c-4084-986a-2db1e4678e16">

**Comment by joyous-coder** [comment]
Nice job. Thanks!!!
