### ISSUE TITLE
Radar chart

### ISSUE THREAD

**Issue by qacizar** [caronchen/obsidian-chartsview-plugin#56]
No option to fill areas of Radar chart as shown in Readme.

**Comment by caronchen** [comment]
<img width="330" alt="image" src="https://github.com/caronchen/obsidian-chartsview-plugin/assets/150803/551ba2f7-3b15-45c0-b0a6-cf2eb7b185f9">
<br/>
<img width="500" alt="image" src="https://github.com/caronchen/obsidian-chartsview-plugin/assets/150803/540a2503-b868-4a45-923b-1b95ae4c9fcb">
<br/>
<img width="262" alt="image" src="https://github.com/caronchen/obsidian-chartsview-plugin/assets/150803/d9762abb-2622-46fb-89a1-78b17a074785">
OR
<img width="242" alt="image" src="https://github.com/caronchen/obsidian-chartsview-plugin/assets/150803/cc22c149-6815-453c-8895-4b944938d773">
<br/>
<img width="472" alt="image" src="https://github.com/caronchen/obsidian-chartsview-plugin/assets/150803/4f2d1f8e-c7ac-4507-9754-0b2bcb6f7b96">

**Comment by qacizar** [comment]
Thanks you for reply!

Where to check all the chart options?

**Comment by caronchen** [comment]
> Thanks you for reply!
> 
> Where to check all the chart options?

https://github.com/ant-design/ant-design-charts
