### ISSUE TITLE
[需求]建议增加数据从CSV文件导入和读取功能

### ISSUE THREAD

**Issue by sherjf** [caronchen/obsidian-chartsview-plugin#7]
遇到数据量较大的图表，使用yaml语法太麻烦且很长。建议插件增加导入CSV文件，从CSV文件读取图表数据的功能。

**Comment by caronchen** [comment]
> 遇到数据量较大的图表，使用yaml语法太麻烦且很长。建议插件增加导入CSV文件，从CSV文件读取图表数据的功能。

1.0.5 版本已经发布支持。
