### ISSUE TITLE
建议完善函数功能，谢谢！

### ISSUE THREAD

**Issue by sherjf** [caronchen/obsidian-chartsview-plugin#8]
以下代码使用中出错，显示不支持嵌套，建议完善下函数功能，谢谢！
 eachView: function eachView(view, f) {
      return {
        type: 'pie',
        options: {
          data: f.data,
          angleField: 'mean',
          colorField: 'cut',
          pieStyle: { stroke: null },
        },
      };
    },

**Comment by caronchen** [comment]
改成这样试试：
```
eachView: |
  function eachView(view, f) {
    return {
      type: 'pie',
      options: {
        data: f.data,
        angleField: 'mean',
        colorField: 'cut',
        pieStyle: { stroke: null }
      }
    };
  }
```

**Comment by sherjf** [comment]
现在不报错了，但图出不来，请帮忙查看修正，谢谢！
```chartsview
type: Facet
data: [
  {type: A, ratio: 0.44},
  {type: B, ratio: 0.3},
]
options:
  type: 'rect'
  fields: ['type']
  eachView: |
    function eachView(view, f){
	  return {
	    type: 'pie',
	    options: {
	      data: f.data,
		  angleField: 'ratio',
		  colorField: 'type',
		  pieStyle: {stroke: null},
	    },
	  };
	}
```

**Comment by caronchen** [comment]
> Facet

Facet是新版本的功能，待我更新版本后再试。

**Comment by caronchen** [comment]
> 现在不报错了，但图出不来，请帮忙查看修正，谢谢！
> 
> ```
> type: Facet
> data: [
>   {type: A, ratio: 0.44},
>   {type: B, ratio: 0.3},
> ]
> options:
>   type: 'rect'
>   fields: ['type']
>   eachView: |
>     function eachView(view, f){
> 	  return {
> 	    type: 'pie',
> 	    options: {
> 	      data: f.data,
> 		  angleField: 'ratio',
> 		  colorField: 'type',
> 		  pieStyle: {stroke: null},
> 	    },
> 	  };
> 	}
> ```

更新新版本再试一下吧。我已经升级了。

**Comment by sherjf** [comment]
谢谢！确实可以了，但数据引用不了，如下：
```chartsview
type: Facet
data: [
  {type: A, ratio: 0.4, p: 0.3},
  {type: B, ratio: 0.3, p: 0.2},
  {type: C, ratio: 0.2, p: 0.1},
]
options:
  height: 260
  type: 'rect'
  fields: ['type']
  eachView: |
    function eachView(view, f){
	  return {
	    type: 'gauge',
	    options: {
		  data: f.data,
		  radius: 1,
		  range: {
		    ticks: [0, 'ratio', 1],
			color: ['hsl(150,50%,65%)', 'l(0) 0:hsl(60,50%,50%) 1:hsl(0,50%,50%)'],
		  },
		  indicator: {
            pointer: {
              style: {stroke: 'hsl(35,50%,65%)'}
			},
			pin: {
              style: {stroke: 'hsl(35,50%,65%)'}
			},
		  },
		  percent: ['p'],
	    }
	  }
	}
```
分面中的ticks、percent如何引用data中的数据，请指教，谢谢！
